//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfdemo0403.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public string Номер_заказа { get; set; }
        public Nullable<System.DateTime> Дата_заказа { get; set; }
        public System.DateTime Дата_доставки { get; set; }
        public int Код_пункта_выдачи { get; set; }
        public int Код_клиента { get; set; }
        public string Код_для_получения { get; set; }
    }
}
