//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfdemo0403.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Единица_измерения { get; set; }
        public string Цена { get; set; }
        public string Поставщик { get; set; }
        public string Производитель { get; set; }
        public string Категория { get; set; }
        public int Скидка { get; set; }
        public int Количество_на_складе { get; set; }
        public string Описание { get; set; }
        public byte[] Фото { get; set; }

        public string FullImagePath
        {
            get
            {
                return string.IsNullOrEmpty(this.Фото?.ToString())
                    ? "/images/picture.png"
                    : $"/images/{this.Фото}";
            }
        }

        
        public decimal Цена_со_скидкой
        {
            get
            {
                if (decimal.TryParse(Цена, out decimal priceDecimal))
                {
                    decimal discount = (decimal)Скидка;
                    return priceDecimal * (1 - discount / 100);
                }
                return 0; 
            }
        }
    }
}
